---
title: "ALK_ExonImbalance_SKCM_Analysis"
author: "Haider Inam"
date: "2/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")
```

```{r}
library(knitr)
library(tictoc)
library(workflowr)
library(VennDiagram)
library(dplyr)
library(foreach)
library(doParallel)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(devtools)
library(ggsignif)
source("code/contab_maker.R")
source("code/alldata_compiler.R")
source("code/quadratic_solver.R")
source("code/mut_excl_genes_generator.R")
source("code/mut_excl_genes_datapoints.R")
source("code/simresults_generator.R")

######################Cleanup for GGPlot2#########################################
cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"))
```

Making ALK Expression the plots:
```{r}
alkati_merged_data=read.csv("output/all_data_skcm.csv")
alkati_merged_data$alkati=0
alkati_merged_data$alkati[alkati_merged_data$Ratio>=10&alkati_merged_data$mRNA_count>=500&alkati_merged_data$RSEM_normalized>=100]=1
alkati_merged_data$alkati=factor(alkati_merged_data$alkati,levels=c("1","0"))

  ggplot(alkati_merged_data,aes(x=mean_RPKM_1.19, y=mean_RPKM_20.29,color=factor(alkati)))+
    geom_abline(size=1)+
    geom_point(size=4)+
    ####Had to add this line to not overplot the alkati datapoint- Haider 1/31/19
    geom_point(data=alkati_merged_data[alkati_merged_data$alkati==1,],aes(x=mean_RPKM_1.19, y=mean_RPKM_20.29,color=factor(alkati)),size=4)+
    scale_x_continuous(trans = "log10",name="Exon 1:19 RPKM",breaks=c(1e-2,1e0,1e2),labels = parse(text = c("10^-2","10^0","10^2")),limits = c(1e-3,1e3))+
    scale_y_continuous(trans = "log10",name="Exon 20:29 RPKM",breaks=c(1e-2,1e0,1e2),labels = parse(text = c("10^-2","10^0","10^2")),limits = c(1e-3,1e3))+
    scale_color_brewer(palette="Set1",name="ALKATI",labels=c("Yes", "No"))+
    cleanup+
    theme(plot.title = element_text(hjust=.5),
          text = element_text(size=24,face = "bold"),
          axis.title = element_text(face="bold",size="24"),
          axis.text=element_text(face="bold",size="24",colour = "black"))+
    theme(legend.key.size = unit(30,"pt"))
# ggsave("output/alkati_skcm_exonimbalance.pdf",width =12 ,height =10 ,units = "in",useDingbats=F)

#Testing if both kinase and ALK expression are different
ks.test(alkati_merged_data$mean_RPKM_1.19,alkati_merged_data$mean_RPKM_20.29)
###We observed a significant difference between the distribution for the 20-29 exons and the 1-19 exons The reported p-value was 2-16.

```

