---
title: "Subsampling Simulations for ALKATI"
author: "Haider Inam"
date: "1/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")
```

```{r,include=F}
library(plotly)
library(knitr)
library(tictoc)
library(workflowr)
library(VennDiagram)
library(dplyr)
library(foreach)
library(doParallel)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(devtools)
library(ggsignif)
library(extrafont)
source("code/contab_maker.R")
source("code/alldata_compiler.R")
source("code/quadratic_solver.R")
source("code/mut_excl_genes_generator.R")
source("code/mut_excl_genes_datapoints.R")
source("code/simresults_generator.R")

######################Cleanup for GGPlot2#########################################
cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"))
```
###Mutual Exclusivity for ALKATI data without down sampling
```{r}
  nameposctrl1<-'BRAF'
  #Positive control 1
  nameposctrl2<-'NRAS'
  #Oncogene in Question
  namegene<-'ATI'
  #Mutation Boolean (Y or N)
  mtn<-'N'
  #Name Mutation for Positive Ctrl 1
  nameposctrl1mt<-'V600E'
  #Name of Mutation for Positive Ctrl 2
  nameposctrl2mt<-'Q61L'

alldata=read.csv("output/all_data_skcm.csv",sep=",",header=T,stringsAsFactors=F)
head(alldata)
###Not mutation specific
alldata_comp=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,'N',"N/A","N/A")[[2]]
head(alldata_comp)
BRAF_NRAS=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$Positive_Ctrl2,alldata_comp))$p.value
BRAF_NRAS_odds=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$Positive_Ctrl2,alldata_comp))$estimate
BRAF_ATI=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$genex,alldata_comp))$p.value
BRAF_ATI_odds=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$genex,alldata_comp))$estimate
NRAS_ATI=fisher.test(contab_maker(alldata_comp$Positive_Ctrl2,alldata_comp$genex,alldata_comp))$p.value
NRAS_ATI_odds=fisher.test(contab_maker(alldata_comp$Positive_Ctrl2,alldata_comp$genex,alldata_comp))$estimate
Rndm_ATI=fisher.test(contab_maker(alldata_comp$rndmarray,alldata_comp$genex,alldata_comp))$p.value
Rndm_ATI_odds=fisher.test(contab_maker(alldata_comp$rndmarray,alldata_comp$genex,alldata_comp))$estimate
###Mutation specific
alldata_comp=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,'Y',"V600E","Q61L")[[2]]
head(alldata_comp)
BRAF_NRAS_mtn=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$Positive_Ctrl2,alldata_comp))$p.value
BRAF_NRAS_mtn_odds=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$Positive_Ctrl2,alldata_comp))$estimate
BRAF_ATI_mtn=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$genex,alldata_comp))$p.value
BRAF_ATI_mtn_odds=fisher.test(contab_maker(alldata_comp$Positive_Ctrl1,alldata_comp$genex,alldata_comp))$estimate
NRAS_ATI_mtn=fisher.test(contab_maker(alldata_comp$Positive_Ctrl2,alldata_comp$genex,alldata_comp))$p.value
NRAS_ATI_mtn_odds=fisher.test(contab_maker(alldata_comp$Positive_Ctrl2,alldata_comp$genex,alldata_comp))$estimate
Rndm_ATI_mtn=fisher.test(contab_maker(alldata_comp$rndmarray,alldata_comp$genex,alldata_comp))$p.value
Rndm_ATI_mtn_odds=fisher.test(contab_maker(alldata_comp$rndmarray,alldata_comp$genex,alldata_comp))$estimate

###Summarizing ME data in a table:
alkati_me_summary=data.frame(cbind(rbind(BRAF_ATI,BRAF_ATI_mtn,NRAS_ATI,NRAS_ATI_mtn,BRAF_NRAS,BRAF_NRAS_mtn,Rndm_ATI,Rndm_ATI_mtn),rbind(BRAF_ATI_odds,BRAF_ATI_mtn_odds,NRAS_ATI_odds,NRAS_ATI_mtn_odds,BRAF_NRAS_odds,BRAF_NRAS_mtn_odds,Rndm_ATI_odds,Rndm_ATI_mtn_odds)))
colnames(alkati_me_summary)=c("P.value","Odds.Ratio")
alkati_me_summary
```

###P-value distribution plots for Figure 1B:
```{r}
nsubsamples=50 # maybe this can be removed and instead calculated later.
  nsims<-100 #
  #Positive control 1
  nameposctrl1<-'BRAF'
  #Positive control 1
  nameposctrl2<-'NRAS'
  #Oncogene in Question
  namegene<-'ATI'
  #Mutation Boolean (Y or N)
  mtn<-'N'
  #Name Mutation for Positive Ctrl 1
  nameposctrl1mt<-'V600E'
  #Name of Mutation for Positive Ctrl 2
  nameposctrl2mt<-'Q61L'
  
  alldata=read.csv("output/all_data_skcm.csv",sep=",",header=T,stringsAsFactors=F)
  nexperiments=7
alldata_comp=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,mtn,"N/A","N/A")[[2]]
genex_replication_prop=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,mtn,"N/A","N/A")[[1]]
simresults_comb=data.frame()
for(subsample_number in c(seq(5,25,5))){
  nsubsamples=subsample_number
  simresults=simresults_generator(alldata_comp,7)
  simresults_comb=rbind(simresults_comb,simresults) ##iterative rbind this is not the most efficient way to do this
}
```


```{r}

simresults_concat=simresults_comb%>%
  filter(exp_num%in%c(4))
# simresults_concat=simresults_comb
plotly=ggplot(simresults_concat,aes(x=factor(subsample_size),y=log10(p_val)))+
  geom_boxplot()+
  cleanup+
  guides(fill=F)+
  scale_y_continuous(name="log P-Value")+
  scale_x_discrete(name="Subsample size")+
  # scale_color_manual(values="#E78AC3")+
  theme(plot.title = element_text(hjust=.5),
      text = element_text(size=11,face="bold"),
      axis.title = element_text(face="bold",size="12",color="black"),
      axis.text=element_text(face="bold",size="11",color="black"))
ggplotly(plotly)
# font_import()
# windowsFonts(Arial = windowsFont("Arial"))
# ggsave("output/alkati_subsamplesize_pval_fig1c.pdf",width = 3,height = 2,units = "in",useDingbats=F)

max(simresults_concat$OR_val)
plotly=ggplot(simresults_concat,aes(x=factor(subsample_size),y=(OR_val)))+
  geom_boxplot()+
  cleanup+
  guides(fill=F)+
  scale_y_continuous(name="log OR")+
  scale_x_discrete(name="Subsample size")+
  # scale_color_manual(values="#E78AC3")+
  theme(plot.title = element_text(hjust=.5),
      text = element_text(size=12,face="bold"),
      axis.title = element_text(face="bold",size="12",color="black"),
      axis.text=element_text(face="bold",size="12",color="black"))

ggplotly(plotly)
# ggsave("output/alkati_subsamplesize_orval_fig1c.pdf",width = 3,height = 2,units = "in",useDingbats=F)
  # geom_hline(yintercept=-1.59,size=1)


```

###Adding simulations for comparisons with mutations:
```{r}
nsubsamples=12 # maybe this can be removed and instead calculated later.
  nsims<-100 #
  #Positive control 1
  nameposctrl1<-'BRAF'
  #Positive control 1
  nameposctrl2<-'NRAS'
  #Oncogene in Question
  namegene<-'ATI'
  #Mutation Boolean (Y or N)
  mtn<-'Y'
  #Name Mutation for Positive Ctrl 1
  nameposctrl1mt<-'V600E'
  #Name of Mutation for Positive Ctrl 2
  nameposctrl2mt<-'Q61L'
  

  alldata=read.csv("output/all_data_skcm.csv",sep=",",header=T,stringsAsFactors=F)
  nexperiments=7
###For mutation
alldata_comp=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,mtn,nameposctrl1mt,nameposctrl2mt)[[2]]
genex_replication_prop=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,mtn,nameposctrl1mt,nameposctrl2mt)[[1]]
  simresults=simresults_generator(alldata_comp,7)
simresults$mtn='Y'

####For no mutation
mtn='N'
alldata_comp=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,mtn,"N/A","N/A")[[2]]
genex_replication_prop=alldata_compiler(alldata,nameposctrl1,nameposctrl2,namegene,mtn,"N/A","N/A")[[1]]
  simresults_nomtn=simresults_generator(alldata_comp,7)
simresults_nomtn$mtn='N'

simresults=rbind(simresults,simresults_nomtn)

```


### Generating the P-value plots for Figure 2. Will show ati vs braf, ati vs nras, for with-muts and without-muts
```{r}
simresults[simresults$exp_num==1,]$exp_name="BRAF & ALKATI"
simresults[simresults$exp_num==3,]$exp_name="NRAS & ALKATI"
simresults[simresults$exp_num==4,]$exp_name="BRAF & NRAS"
simresults$exp_name=factor(simresults$exp_name,levels=c("1","5","6","7","BRAF & ALKATI","NRAS & ALKATI","BRAF & NRAS"))
simresults$mtn_tag='N'
simresults[simresults$mtn=='Y',]$mtn_tag="Mutation-specific"
simresults[simresults$mtn=='N',]$mtn_tag="Non mutation-specific"

simresults$mtn_tag=factor(simresults$mtn_tag,levels=c("Non mutation-specific","Mutation-specific"))
simresults_concat=simresults%>%
  filter(exp_num==c(1,3,4))

plotly=ggplot(simresults_concat,aes(x=factor(exp_name),y=log10(p_val)))+
  geom_boxplot(aes(fill=factor(exp_name)))+
  facet_wrap(~factor(mtn_tag))+
  cleanup+
  guides(fill=F)+
  scale_y_continuous(name="log P-Value",limits = c(NA,1.5))+
  scale_x_discrete(name="Gene Pair")+
  scale_fill_brewer(palette = "Set2",name="Gene Pair")+
  theme(plot.title = element_text(hjust=.5),
      text = element_text(size=12,face="bold"),
      axis.title = element_text(face="bold",size="13",color="black"),
      axis.text.x=element_text(angle=15,hjust=.5,vjust=.5),
      axis.text=element_text(face="bold",size="9",color="black"))
ggplotly(plotly)
# ggsave("output/alkati_mtn_pval_fig2B.pdf",width = 6,height = 4,units = "in",useDingbats=F)


###Performing the KS. test on these to show that the distribtutions of BRAF NRAS and BRAF ALKATI/NRAS ALKATI are significantly different .
# Mutation-specific
brafati=simresults_concat%>%filter(mtn_tag=="Mutation-specific",exp_num==1)
nrasati=simresults_concat%>%filter(mtn_tag=="Mutation-specific",exp_num==3)
brafnras=simresults_concat%>%filter(mtn_tag=="Mutation-specific",exp_num==4)

ks.test(brafati$p_val,brafnras$p_val)$p.value
ks.test(nrasati$p_val,brafnras$p_val)$p.value
ks.test(brafati$p_val,nrasati$p_val)$p.value
# Non-mutation-specific
brafati=simresults_concat%>%filter(mtn_tag=="Non mutation-specific",exp_num==1)
nrasati=simresults_concat%>%filter(mtn_tag=="Non mutation-specific",exp_num==3)
brafnras=simresults_concat%>%filter(mtn_tag=="Non mutation-specific",exp_num==4)

ks.test(brafati$p_val,brafnras$p_val)$p.value
ks.test(nrasati$p_val,brafnras$p_val)$p.value
ks.test(brafati$p_val,nrasati$p_val)$p.value
```

